# Generated by Django 5.0.6 on 2024-09-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_colorvarient_sizevarient_product_color_varient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
