# Generated by Django 5.0.6 on 2024-09-25 11:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_product_description_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('coupon_code', models.CharField(max_length=50)),
                ('is_expire', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default=500)),
                ('min_amount', models.IntegerField(default=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
